// <auto-generated />
namespace FilMoviesAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_password_length : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_password_length));
        
        string IMigrationMetadata.Id
        {
            get { return "201803071253205_update_password_length"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
