// <auto-generated />
namespace FilMoviesAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_watchedmovie_add_date : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_watchedmovie_add_date));
        
        string IMigrationMetadata.Id
        {
            get { return "201803061915327_update_watchedmovie_add_date"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
